// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eltxnqwboyqhhvruyvlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdHhucXdib3lxaGh2cnV5dmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTU4NDYsImV4cCI6MjA3MDI3MTg0Nn0.tajoRHA4Yaz4vVPPpT040T4C15EThGzrrGeUQTFKNyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});